http://localhost:37100/project

###

http://localhost:37100/api/project
Content-Type: application/json

{
  "projectId": 16
}

###

POST http://localhost:37100/api/project
Content-Type: application/json

{
  "name": "test"
}

###

PUT http://localhost:37100/api/project
Content-Type: application/json

{
  "projectId": 16,
  "name": "Hello"
}

###